[keypoints]
"nose" = {id=0, color=[40,40,255]}
"left_eye"= {id=1, color=[250,70,70]}
"right_eye"= {id=2, color=[50,250,50]}
"left_ear"= {id=3, color=[250,70,70]}
"right_ear"= {id=4, color=[50,250,50]}
"left_shoulder"= {id=5, color=[250,70,70]}
"right_shoulder"= {id=6, color=[50,250,50]}
"left_elbow"= {id=7, color=[250,70,70]}
"right_elbow"= {id=8, color=[50,250,50]}
"left_wrist"= {id=9, color=[250,70,70]}
"right_wrist"= {id=10, color=[50,250,50]}
"left_hip"= {id=11, color=[250,70,70]}
"right_hip"= {id=12, color=[50,250,50]}
"left_knee"= {id=13, color=[250,70,70]}
"right_knee"= {id=14, color=[50,250,50]}
"left_ankle"= {id=15, color=[250,70,70]}
"right_ankle"= {id=16, color=[50,250,50]}
"left_big_toe"= {id=17, color=[250,70,70]}
"left_small_toe"= {id=18, color=[250,70,70]}
"left_heel"= {id=19, color=[250,70,70]}
"right_big_toe"= {id=20, color=[50,250,50]}
"right_small_toe"= {id=21, color=[50,250,50]}
"right_heel"= {id=22, color=[50,250,50]}
"face_1"={id=23, color=[40,40,200]}
"face_2"={id=24, color=[40,40,200]}
"face_3"={id=25, color=[40,40,200]}
"face_4"={id=26, color=[40,40,200]}
"face_5"={id=27, color=[40,40,200]}
"face_6"={id=28, color=[40,40,200]}
"face_7"={id=29, color=[40,40,200]}
"face_8"={id=30, color=[40,40,200]}
"face_9"={id=31, color=[40,40,200]}
"face_10"={id=32, color=[40,40,200]}
"face_11"={id=33, color=[40,40,200]}
"face_12"={id=34, color=[40,40,200]}
"face_13"={id=35, color=[40,40,200]}
"face_14"={id=36, color=[40,40,200]}
"face_15"={id=37, color=[40,40,200]}
"face_16"={id=38, color=[40,40,200]}
"face_17"={id=39, color=[40,40,200]}
"right_eyeblow_1"={id=40, color=[50,250,50]}
"right_eyeblow_2"={id=41, color=[50,250,50]}
"right_eyeblow_3"={id=42, color=[50,250,50]}
"right_eyeblow_4"={id=43, color=[50,250,50]}
"right_eyeblow_5"={id=44, color=[50,250,50]}
"left_eyeblow_1"={id=45, color=[250,70,70]}
"left_eyeblow_2"={id=46, color=[250,70,70]}
"left_eyeblow_3"={id=47, color=[250,70,70]}
"left_eyeblow_4"={id=48, color=[250,70,70]}
"left_eyeblow_5"={id=49, color=[250,70,70]}
"nose_1"={id=50, color=[40,40,200]}
"nose_2"={id=51, color=[40,40,200]}
"nose_3"={id=52, color=[40,40,200]}
"nose_4"={id=53, color=[40,40,200]}
"nose_5"={id=54, color=[40,40,200]}
"nose_6"={id=55, color=[40,40,200]}
"nose_7"={id=56, color=[40,40,200]}
"nose_8"={id=57, color=[40,40,200]}
"nose_9"={id=58, color=[40,40,200]}
"right_eye_1"={id=59, color=[50,250,50]}
"right_eye_2"={id=60, color=[50,250,50]}
"right_eye_3"={id=61, color=[50,250,50]}
"right_eye_4"={id=62, color=[50,250,50]}
"right_eye_5"={id=63, color=[50,250,50]}
"right_eye_6"={id=64, color=[50,250,50]}
"left_eye_1"={id=65, color=[250,70,70]}
"left_eye_2"={id=66, color=[250,70,70]}
"left_eye_3"={id=67, color=[250,70,70]}
"left_eye_4"={id=68, color=[250,70,70]}
"left_eye_5"={id=69, color=[250,70,70]}
"left_eye_6"={id=70, color=[250,70,70]}
"mouth_1"={id=71, color=[40,40,200]}
"mouth_2"={id=72, color=[40,40,200]}
"mouth_3"={id=73, color=[40,40,200]}
"mouth_4"={id=74, color=[40,40,200]}
"mouth_5"={id=75, color=[40,40,200]}
"mouth_6"={id=76, color=[40,40,200]}
"mouth_7"={id=77, color=[40,40,200]}
"mouth_8"={id=78, color=[40,40,200]}
"mouth_9"={id=79, color=[40,40,200]}
"mouth_10"={id=80, color=[40,40,200]}
"mouth_11"={id=81, color=[40,40,200]}
"mouth_12"={id=82, color=[40,40,200]}
"mouth_13"={id=83, color=[40,40,200]}
"mouth_14"={id=84, color=[40,40,200]}
"mouth_15"={id=85, color=[40,40,200]}
"mouth_16"={id=86, color=[40,40,200]}
"mouth_17"={id=87, color=[40,40,200]}
"mouth_18"={id=88, color=[40,40,200]}
"mouth_19"={id=89, color=[40,40,200]}
"mouth_20"={id=90, color=[40,40,200]}
"left_hand_1"={id=91, color=[250,70,70]}
"left_hand_2"={id=92, color=[250,70,70]}
"left_hand_3"={id=93, color=[250,70,70]}
"left_hand_4"={id=94, color=[250,70,70]}
"left_hand_5"={id=95, color=[250,70,70]}
"left_hand_6"={id=96, color=[250,70,70]}
"left_hand_7"={id=97, color=[250,70,70]}
"left_hand_8"={id=98, color=[250,70,70]}
"left_hand_9"={id=99, color=[250,70,70]}
"left_hand_10"={id=100, color=[250,70,70]}
"left_hand_11"={id=101, color=[250,70,70]}
"left_hand_12"={id=102, color=[250,70,70]}
"left_hand_13"={id=103, color=[250,70,70]}
"left_hand_14"={id=104, color=[250,70,70]}
"left_hand_15"={id=105, color=[250,70,70]}
"left_hand_16"={id=106, color=[250,70,70]}
"left_hand_17"={id=107, color=[250,70,70]}
"left_hand_18"={id=108, color=[250,70,70]}
"left_hand_19"={id=109, color=[250,70,70]}
"left_hand_20"={id=110, color=[250,70,70]}
"left_hand_21"={id=111, color=[250,70,70]}
"right_hand_1"={id=112, color=[50,250,50]}
"right_hand_2"={id=113, color=[50,250,50]}
"right_hand_3"={id=114, color=[50,250,50]}
"right_hand_4"={id=115, color=[50,250,50]}
"right_hand_5"={id=116, color=[50,250,50]}
"right_hand_6"={id=117, color=[50,250,50]}
"right_hand_7"={id=118, color=[50,250,50]}
"right_hand_8"={id=119, color=[50,250,50]}
"right_hand_9"={id=120, color=[50,250,50]}
"right_hand_10"={id=121, color=[50,250,50]}
"right_hand_11"={id=122, color=[50,250,50]}
"right_hand_12"={id=123, color=[50,250,50]}
"right_hand_13"={id=124, color=[50,250,50]}
"right_hand_14"={id=125, color=[50,250,50]}
"right_hand_15"={id=126, color=[50,250,50]}
"right_hand_16"={id=127, color=[50,250,50]}
"right_hand_17"={id=128, color=[50,250,50]}
"right_hand_18"={id=129, color=[50,250,50]}
"right_hand_19"={id=130, color=[50,250,50]}
"right_hand_20"={id=131, color=[50,250,50]}
"right_hand_21"={id=132, color=[50,250,50]}

[keypoint_group]
"head" = [0, 1, 2, 3, 4]
"face" = [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90]
"body" = [5, 6, 11, 12]
"arms" = [7, 8, 9, 10]
"hands" = [91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132]
"legs" = [13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

[draw]
labels = ["nose", "left_shoulder", "right_shoulder"]
mask = ["nose", "left_ear", "right_ear", "left_eye", "right_eye"]

[bones]
bones = [
    ["left_shoulder", "right_shoulder"],
    ["left_shoulder", "left_hip"],
    ["right_shoulder", "right_hip"],
    ["left_hip", "right_hip"],
    ["left_shoulder", "left_elbow"],
    ["left_elbow", "left_wrist"],
    ["right_shoulder", "right_elbow"],
    ["right_elbow", "right_wrist"],
    ["left_hip", "left_knee"],
    ["left_knee", "left_ankle"],
    ["right_hip", "right_knee"],
    ["right_knee", "right_ankle"],
    ["left_ankle", "left_heel"],
    ["left_ankle", "left_big_toe"],
    ["left_ankle", "left_small_toe"],
    ["right_ankle", "right_heel"],
    ["right_ankle", "right_big_toe"],
    ["right_ankle", "right_small_toe"],
    ["right_hand_1", "right_hand_2"],
    ["right_hand_2", "right_hand_3"],
    ["right_hand_3", "right_hand_4"],
    ["right_hand_4", "right_hand_5"],
    ["right_hand_1", "right_hand_6"],
    ["right_hand_1", "right_hand_18"],
    ["right_hand_6", "right_hand_7"],
    ["right_hand_7", "right_hand_8"],
    ["right_hand_8", "right_hand_9"],
    ["right_hand_10", "right_hand_11"],
    ["right_hand_11", "right_hand_12"],
    ["right_hand_12", "right_hand_13"],
    ["right_hand_14", "right_hand_14"],
    ["right_hand_15", "right_hand_15"],
    ["right_hand_16", "right_hand_16"],
    ["right_hand_18", "right_hand_19"],
    ["right_hand_19", "right_hand_20"],
    ["right_hand_20", "right_hand_21"],
    ["left_hand_1", "left_hand_2"],
    ["left_hand_2", "left_hand_3"],
    ["left_hand_3", "left_hand_4"],
    ["left_hand_4", "left_hand_5"],
    ["left_hand_1", "left_hand_6"],
    ["left_hand_1", "left_hand_18"],
    ["left_hand_6", "left_hand_7"],
    ["left_hand_7", "left_hand_8"],
    ["left_hand_8", "left_hand_9"],
    ["left_hand_10", "left_hand_11"],
    ["left_hand_11", "left_hand_12"],
    ["left_hand_12", "left_hand_13"],
    ["left_hand_14", "left_hand_15"],
    ["left_hand_15", "left_hand_16"],
    ["left_hand_16", "left_hand_17"],
    ["left_hand_18", "left_hand_19"],
    ["left_hand_19", "left_hand_20"],
    ["left_hand_20", "left_hand_21"],
]

threshold = 0.4