[keypoints]
"nose" = {id=0, color=[40,40,255]}
"left_eye"= {id=1, color=[250,70,70]}
"right_eye"= {id=2, color=[50,250,50]}
"left_ear"= {id=3, color=[250,70,70]}
"right_ear"= {id=4, color=[50,250,50]}
"left_shoulder"= {id=5, color=[250,70,70]}
"right_shoulder"= {id=6, color=[50,250,50]}
"left_elbow"= {id=7, color=[250,70,70]}
"right_elbow"= {id=8, color=[50,250,50]}
"left_wrist"= {id=9, color=[250,70,70]}
"right_wrist"= {id=10, color=[50,250,50]}
"left_hip"= {id=11, color=[250,70,70]}
"right_hip"= {id=12, color=[50,250,50]}
"left_knee"= {id=13, color=[250,70,70]}
"right_knee"= {id=14, color=[50,250,50]}
"left_ankle"= {id=15, color=[250,70,70]}
"right_ankle"= {id=16, color=[50,250,50]}
"head"= {id=17, color=[40,40,255]}
"neck"= {id=18, color=[40,40,255]}
"hip"= {id=19, color=[40,40,255]}
"left_big_toe"= {id=20, color=[250,70,70]}
"right_big_toe"= {id=21, color=[50,250,50]}
"left_small_toe"= {id=22, color=[250,70,70]}
"right_small_toe"= {id=23, color=[50,250,50]}
"left_heel"= {id=24, color=[250,70,70]}
"right_heel"= {id=25, color=[50,250,50]}

[keypoint_group]
"body" = [5, 6, 11, 12, 18, 19]
"arms" = [7, 8, 9, 10]
"legs" = [13, 14, 15, 16]

[draw]
labels = ["head", "left_shoulder", "right_shoulder"]
mask = ["nose", "left_ear", "right_ear", "left_eye", "right_eye"]

[bones]
bones = [
    ["left_shoulder", "neck"],
    ["neck", "right_shoulder"],
    ["left_shoulder", "left_hip"],
    ["right_shoulder", "right_hip"],
    ["left_hip", "hip"],
    ["hip", "right_hip"],
    ["left_shoulder", "left_elbow"],
    ["left_elbow", "left_wrist"],
    ["right_shoulder", "right_elbow"],
    ["right_elbow", "right_wrist"],
    ["left_hip", "left_knee"],
    ["left_knee", "left_ankle"],
    ["right_hip", "right_knee"],
    ["right_knee", "right_ankle"],
    ["left_ankle", "left_heel"],
    ["left_ankle", "left_big_toe"],
    ["left_ankle", "left_small_toe"],
    ["right_ankle", "right_heel"],
    ["right_ankle", "right_big_toe"],
    ["right_ankle", "right_small_toe"],
]

threshold = 0.4